### ISSUE TITLE
Error cannot read EDSDK.dll

### ISSUE THREAD

**Issue by paoolea** [elliotwoods/ofxCanon#1]
Hi,

I'm using Windows 10 and OF 0.9.0 I downloaded the Canon SDK 3.4 and I have de EDSDK.dll but I don't know why I have this problem.

Severity    Code    Description Project File    Line    Suppression State
Error   LNK1107 invalid or corrupt file: cannot read at 0x2C8   CanonV2 ..\addons\ofxCanon-master\libs\EDSDK\bin\vs\Win32\EDSDK.dll 1

**Comment by elliotwoods** [comment]
visual studio shouldn't be trying to link a dll. so i'm confused why this error message appears
please try 
https://drive.google.com/file/d/0B_S1z3_AWMRSLXprRzBaaDIyb1U/view?usp=sharing

**Comment by elliotwoods** [comment]
seems we fixed this over email
