### ISSUE TITLE
OSX with current master branch of OF

### ISSUE THREAD

**Issue by fred-dev** [elliotwoods/ofxCanon#4]
When running the examples I get 

`[warning] ofxCanon: Delete directory item failed with error INTERNAL_ERROR`

Every time I try to take a photo. It works fine for me on windows though..

It fails on this line
   ` return (*__f_)(_VSTD::forward<_ArgTypes>(__arg)...);`

line 1817 of funcitonal.cpp

OSX 10.12.6
Xcode 8.3.2

**Comment by elliotwoods** [comment]
I’m going to close this. @stephanschulz recently tested on OSX XCode
