### ISSUE TITLE
EOS-1D X issues

### ISSUE THREAD

**Issue by stephanschulz** [elliotwoods/ofxCanon#8]
I am starting this thread with the hope that at the end (some day) the EOS-1D X will play nice with this addon.

So far I learned that plugging the camera in via it's USB mini port with it's battery powering the camera I get this error message when running the [example](https://github.com/elliotwoods/ofxCanon/tree/master/example)
The app does not run.

<img width="1400" alt="Screen Shot 2020-10-09 at 3 42 36 PM" src="https://user-images.githubusercontent.com/1054816/95625185-19b1c000-0a46-11eb-8ce6-d1625bc14b96.png">
here the error test:
https://gist.github.com/stephanschulz/1119ed6c709dcada00ee56f451826947

I then downloaded the [EOS utility tool](https://canoncanada.custhelp.com/app/answers/answer_view/a_id/1013692/~/eos-utility-3.9.0-for-mac-os-x)

When I use the EOS utility tool it is able to get live view access and other controls.
With the EOS utility running I can now start the OF example app with similar error printed in the console. But it start running. BUT it can't connect to the camera, probably because the EOS utility already has control.
`[ error ] ofxCanon: Open session failed with error COMM_PORT_IS_IN_USE`

<img width="1680" alt="Screen Shot 2020-10-09 at 3 50 34 PM" src="https://user-images.githubusercontent.com/1054816/95626226-e708c700-0a47-11eb-887e-835180a10790.png">

**Comment by stephanschulz** [comment]
I should mention that I did install the EDSDK3500CD(3.5.0) SDK as per the readme. 
Xcode 10.3
macOS 10.14.6
OF 0.11.0

**Comment by stephanschulz** [comment]
following these steps to remove some parts of the SDK did not help either.
https://stackoverflow.com/questions/45551810/edsdk-3-6-macos-32bit-vs-64bit-and-linking-errors

**Comment by stephanschulz** [comment]
What worked is using the EDSDK3900CD(3.9.0) version of the SDK.
I even could leave the development target at 10.9 which OF 0.11 seems to have as default.

All seems good. Yeah.

**Comment by elliotwoods** [comment]
Thanks for posting and fixing!
Perhaps you could edit the readme.md to add an entry to the “## Tested” section. (Perhaps hyperlinking to here)

Ie which camera, platform, SDK version combination worked for you.

That could be a way to close this issue
